POST http://localhost:3000/products
content-type: application/json

{
    "nombre": "Remera Nik Ultra-Fit Wide",
    "categorias": ["ropa", "remeras", "deportes", "fitness"],
    "marca": "Nike",
    "precio": 7850,
    "tipo": "remera"
}

###

DELETE http://localhost:3000/products
content-type: application/json

{
    "_id": "6bdcf930-10e6-4816-ae25-db1e6247d231"
}

###

PATCH http://localhost:3000/products
content-type: application/json

{
    "nombre": "Remera Nike Ultra-Wide Fit",
    "precio": 1200
}
