POST http://localhost:3000/products
content-type: application/json

{
    "nombre": "Remera Nik Ultra-Fit Wide",
    "categorias": ["ropa", "remeras", "deportes", "fitness"],
    "marca": "Nike",
    "precio": 7850,
    "tipo": "remera"
}

###

DELETE http://localhost:3000/products
content-type: application/json

{
    "_id": "12e424-e325-436f-8508-48ee6241a582"
}

###

PATCH http://localhost:3000/products
content-type: application/json

{
    "_id": "8b74b33f-6cb3-4298-b9e5-e62e2a03639e",
    "nombre": "23",
    "categorias": ["ropa", "remeras", "deportes", "fitness"],
    "marca": "Nike"
}