POST http://localhost:3000/products
content-type: application/json

{
    "name": "Buzo King Of The Kongo",
    "categories": ["t-shirtss", "sports"],
    "brand": "Nike",
    "price": 7850,
    "type": "remera"    
}

###

DELETE http://localhost:3000/products
content-type: application/json

{
    "_id": "ef488558-b143-4c22-8cfc-eb97eadef56c"
}

###

PATCH http://localhost:3000/products
content-type: application/json

{
    "_id": "ec668bf1-b390-4eae-a6bd-9db64613a04e",
    "type": "Zapatillas"
}

# fetch("http://localhost:3000/products", {
#     method: "POST",
#     headers: {
#         "Content-Type": "application/json"
#     },
#     body: JSON.stringify({
#         "_id": "8b74b33f-6cb3-4298-b9e5-e62e2a03639e",
#         "nombre": "Remera Nik Ultra-Fit Wide",
#         "categorias": ["ropa", "remeras", "deportes", "fitness"],
#         "marca": "Nike",
#         "precio": 7850,
#         "tipo": "remera"
#     })
# })
